### ISSUE TITLE
TIFF

### ISSUE THREAD

**Issue by slevenson** [usnationalarchives/digital-preservation#13]
The use of TIFF is high risk in that it is proprietary to a single company that is not supporting the format and has not done so for years.  No common rendering engine exists and variances in header data probably means no common rendering engine will ever exist.

**Comment by archivistdemon** [comment]
You mean Adobe? when they bought Aldus?  How are they not supporting the format?  And what do you mean no common rendering engine exists?

**Comment by dangormanjr** [comment]
TIFFs are still used commonly for cultural heritage preservation — museum-quality scans of artifacts and files. At least, that's been my experience getting a humanities PhD and working in digital humanities labs. I think the use of TIFFs is widespread enough in the fields of history and art history that NARA can and should preserve them, even if other fields use different file formats as their standard.

**Comment by lljohnston** [comment]
NARA recognizes that it is a commonly used format and considers it to be low risk enough to retain when they are transferred from agencies.
