### ISSUE TITLE
Feedback from your pals at Library of Congress

### ISSUE THREAD

**Issue by kmurmur** [usnationalarchives/digital-preservation#14]
First and foremost, many congrats on this truly massive achievement! So much work went into this and it shows. And we especially applaud the commitment to transparency both in the level of detail but also using GitHub as a feedback mechanism. Kudos all around!

I'm submitting comments in no particular order on behalf of a small review group at the Library of Congress for you to do with what you will but our overall message to our NARA friends is - keep up the good work!  You are definitely pushing the envelope in all the right ways and we appreciate you sharing out to the community.

1. It might be worth including references for some of the foundational/related work on things like Significant Properties work from JISC and/or Gareth Knight as well as for format evaluation and sustainability (such as http://www.loc.gov/preservation/digital/formats/index.html which is near and dear to my heart). Even if NARA put its own spin on things, it would be worthwhile to show that this is part of a larger ecosystem. 
2. It also might be good to include links to other resources when giving specific examples of technical characteristics. Examples might be IASA TC-04 for audio and the FADGI Still Image Guidelines for Still Images.
3. Can you explain a bit more about rationale for transformation? For example, the plan for QuickTime with AAC  suggest transforming to either BWF or MP3 but those would have very different implications - the former presumably for preservation and the latter for access.
4. There's a bit of unevenness across the action plans. Some are quite detailed for each entry while others have references across a broader scope - at just the wrapper level or even the content category level. 
5. I'm curious about the explicit naming of specific software, especially proprietary tools, as preferred tools. As feds, we have usually shied away from this for public docs and instead highlight functionality rather than brand names. Was there a testing protocol to determine what is a preferred tool? Also, we love that there is some emphasis on open source tools.
6. How often would the action plans be updated? I understand from the SOW that the matrix is every 2 years but is it the same for the action plans? With my experience with the Sustainability of Digital Format site, I can attest that this is a really hard row to hoe and keeping up this level of effort and detail is an enormous effort. It will take a village.
7. What happens when a new format arrives? Would it be added to the matrix/action plans on the 2 year cycle?
8. Sometimes, PDF/A is the target transformation format (for NF00374 for example) but other times, PDF is recommended. Is there a criteria or maybe this is still to come?
9. [WikiData](https://www.wikidata.org/wiki/Wikidata:WikiProject_Informatics/File_formats/Lists/File_formats) has a nice mapping from PUIDs to FDDs to the WikiData QID. This could be another data point for the NARA unique number or maybe add the mapping here. 

Again - such a nice resource and we look forward to seeing it evolve and grow! 

Best from Kate 

Kate Murray (she/her)
Digital Collections Management & Services
Library of Congress
kmur@loc.gov
202-707-4894

**Comment by lljohnston** [comment]
Thanks, Kate!

1/2. We know we're lacking some references, including that work, PUIDs, and URIs to Wikidata, LOC, and FADGI.
3. The recommendations are not generalized, they're based on our current infrastructure and staff capabilities. We also need to disambiguate more between archival and public use copies. 
4. The plans were created by a team, so there certainly can be some differences in terms of granularity. Which do you think need more detail?
5. These aren't meant to be generalized recommendations, they're documentation of our current practices and capabilities, which includes the use of proprietary tools. 
6. You're totally right. We're going to need to go to an ongoing annual update for both. 
7. Yes, but we're going to have to go to an annual cycle. 
8. This is to come. But honestly, it depends on what we've received if we have everything we need to create PDF/A. 
9. Yup, Adding in Wikidata URIs is a requirement for the formal release.

**Comment by kmurmur** [comment]
Sounds like you have thought about/have plans for many of what caught our eye! Again, we support this work and look forward to it continuing to grow and evolve.
