### ISSUE TITLE
Make the policy accessible via PAR

### ISSUE THREAD

**Issue by JonTilbury** [usnationalarchives/digital-preservation#15]
To add to the Machine Readable comment, it would be great if the policy could be read using the Preservation Action Registries protocol. This would ensure it can be read straight into other preservation systems for evaluation and ensure some of the ambiguous statements are clarified. 

As a test case we are trying to see how much of this NARA policy can be encoded using PAR which could then be used to send the policy for those organisations that want to copy it or use it as the basis for their own policy. The results so far are promising.

**Comment by lljohnston** [comment]
We're definitely looking at that; we just need to see what we can accomplish in terms of machine readable encoding options for spring of 2020.

**Comment by JonTilbury** [comment]
Please feel free to follow up with the PAR team, we would be very happy to talk you through the options
