### ISSUE TITLE
Which identifier to use for formats? 

### ISSUE THREAD

**Issue by JonTilbury** [usnationalarchives/digital-preservation#16]
The policy and especially the spreadsheet use NARA identifiers but the de-facto standard is Pronom Unique Identifier (PUID). Sometimes a NARA identifier maps onto several PUIDs which can be confusing. It would be great if the policy could reference the relevant PUID at all times.

**Comment by lljohnston** [comment]
That's definitively our goal for the real release post-review of comments - we know we're missing PUIDs and URIs for Wikidata and LOC.
