### ISSUE TITLE
More detail on transform tools

### ISSUE THREAD

**Issue by JonTilbury** [usnationalarchives/digital-preservation#17]
The list of transform tools is useful and comprehensive, thanks. 

However much of the cleverness is in the parameters used, for example in FFMPEG. Will you also be publishing recommended transform parameters or arguments, for example recommended compression when producing JPEG from TIFF for access.

**Comment by lljohnston** [comment]
Not immediately no, but we can certainly look at that for the future.

**Comment by JonTilbury** [comment]
Would go nicely with publishing the preservation policy using PAR
