### ISSUE TITLE
Attachments held within PST and EML

### ISSUE THREAD

**Issue by JonTilbury** [usnationalarchives/digital-preservation#18]
In your email guidelines you say attachments may be held as MIME content within the EML. Surely this is incompatible with the rest of the guidelines where preservation actions are required on the attachment files themselves, but this is impossible if the attachment is embedded withing the EML. I would recommend always taking a copy outside the EML for separate preservation.

Similar logic applied to a PST file. I would recommend unpacking the PST into a folder hierarchy mimicking the Outlook view, then  processing each message as an EML as above. This makes individual messages discoverable and preservable.

**Comment by lljohnston** [comment]
It's a fair point. To be frank, our email processing capabilities for federal records are still in early days and these recommendations are meant to take our current capabilities and system workflows into account.  I'll pass your feedback along to the processing archivists.
