### ISSUE TITLE
Recommendations on Video Migration

### ISSUE THREAD

**Issue by jackdos** [usnationalarchives/digital-preservation#19]
Although AVI is a long established format, migrating to AVI does not seem to be in line with research conducted in Europe under the auspices of the PRE-FORMA project, where the emerging recommendation and focus of work is MKV as a container for the lossless FFV1video codec (http://www.preforma-project.eu/media-type-and-standards.html) . Similarly, MXF seems to be an industry standard on the basis of being an SMPTE supported Standard.

In either case, the fact that all suggested migrations in the Moving Image section seem to be "to AVI" surely makes AVI a de-facto "preferred" format rather than one of several "accepted"?

**Comment by lljohnston** [comment]
It's based primarily on our current capabilities, and may also be part of the disambiguation we need to do in the plans between archival and public use copies. I'll pass this along to our video archivists as part of the review.

**Comment by eengland** [comment]
Sharing the below message on behalf of one of NARA's subject matter experts who worked on the video plans:

NARA is not anti-FFV1 and currently staff are participating in a FADGI working group to investigate and provide input on the adoption of FFV1 as an additional preservation standard for NARA.  When our project was underway we were evaluating this through the lens of NARA's ability to handle various file formats, and while FFV1 has seen adoption around the globe NARA was not in a position to identify FFV1 as a preferred format for ourselves.  AVI has been the most robust format (with little change or adaptation) while other formats have had multiple iterations and/ or cross compatibility issues for us. Given that we have limited ability (funding, staffing, and resources) this was the best choice for us at the time.  We will update this guidance and continue to investigate other file formats and adopt them if we are able.
