### ISSUE TITLE
Clearer distinction between Public Access and archival holding migration suggestions

### ISSUE THREAD

**Issue by jackdos** [usnationalarchives/digital-preservation#20]
In the digital audio section, the expressed preference of format is BWF or FLAC, with MP3 being listed as a Public Access format. In some of your format recommendations below the action is "Transform" to BWF or MP3. I think the implication here is that transformation should be to BWF for long term retention, or MP3 for Public Access. If my interpretation is correct, it might be useful to make a clearer distinction between the purposes of the recommendations; if not, then it would be useful to suggest some minimum quality standards for migrating to MP3 as the "archival" copy.

**Comment by lljohnston** [comment]
You're totally right about your assumption and the need to clarify the difference between the archival file and the public use file.

**Comment by lljohnston** [comment]
We'll continue to iterate through these to clarify which is a preservation option and which might be a public access option. In some cases, transformation to MP3 could be the only option based the tools that can open and transform the original format, so we'll make that clearer.
