### ISSUE TITLE
Request for scalable/machine actionable tools

### ISSUE THREAD

**Issue by jackdos** [usnationalarchives/digital-preservation#21]
The recommended tool sets are comprehensive and very useful, however in many areas there seems to be a leaning to "fat client" GUI tools. These are incredibly useful for practitioners dealing with individual items, or small batches, and where there is scope for some human resource to perform characterisations/migrations/inspections. From a systems implementation point of view, it would be incredibly useful if these could be supplemented with automatable/batch processing tools that can be machine actioned and scaled to run over much larger datasets. In some cases, the same base tool can be used for either approach (LibreOffice and MediaInfo for example both have GUI and CLI implementations), and again, it would be incredibly useful if it could be indicated where this is true.

**Comment by lljohnston** [comment]
The recommendations are based on our current infrastructure capabilities, which are changing every month. We started with already approved GUI/Fat-Client tools that we already have in production; we have a long list of thin client tools to support batch processing that we want to incorporate into our cloud-based processing environment. We're slowly getting the tools through an IT security and operational review process and into production.
