### ISSUE TITLE
Release documentation in machine readable form

### ISSUE THREAD

**Issue by carlwilson** [usnationalarchives/digital-preservation#22]
Are the original documents PDFs or is there a more parse friendly source, e.g. Markdown text, or XML? PDFs could be produced from them but it would allow:
- direct contributions as PRs, git is horrible at handling PDFs; and
- devs to load some of the data into an automated system, e.g. decision support system or registry.

Overall the work is good, I won't be able to finish reviewing today due to personal circumstances but will finish for 8th November 2019. I trust feedback will still prove useful.

**Comment by lljohnston** [comment]
That's definitely our plan once we finish the review of the comments - expect to see it some time in Spring 2020.

**Comment by lljohnston** [comment]
And yes,, all feedback is useful!
