### ISSUE TITLE
Proper packaging for archival use of Adobe Indesign Files, Architecture files, etc. 

### ISSUE THREAD

**Issue by archivistdemon** [usnationalarchives/digital-preservation#24]
I don't see any guidance on maintaining Adobe Indesign files, CAD architecture files,  etc. that may have multiple other files or links- ie fonts, and images for InDesign, or plumping drawings, and Maya snips for fly-throughs of architecture projects.  Keeping these files as PDF proxies does not solve the issue of then breaking the links that makes that file useful for future need for possible use or access.  Any thoughts?

**Comment by lljohnston** [comment]
This is one of the issues that we're facing - we have only a certain capacity in terms of tools/infrastructure, so we're documenting our current decisions. I very much want to preserve all the components of digital design files in a way that we can deliver them in their original state to researchers as well as provide access to the record content through a PDF. We are very much looking for suggestions for tools/practices that can help us expand our capabilities.

**Comment by lljohnston** [comment]
That said, we recently started using a tool called FME in our processing of digital design files that we find very promising. We haven't been using it long enough to share any expertise.

**Comment by archivistdemon** [comment]
Thanks!
