### ISSUE TITLE
Digital Cinema preservation files - reference there could be a sound element as well as picture

### ISSUE THREAD

**Issue by DigitalBedrock1** [usnationalarchives/digital-preservation#29]
DPX is listed as a preservation format for digital cinema. However, that is only a picture format. There should be a reference that preservation audio files could be associated to the picture DPX, if the digital cinema content has sound (eg, not a silent motion picture).

**Comment by lljohnston** [comment]
You're right, they are a container format that includes audio files. We'll add that for our next update.

**Comment by eengland** [comment]
This has been referenced in our forthcoming update.
