### ISSUE TITLE
Software and Code plan - where to locate a copy if not possessed by NARA/this agency

### ISSUE THREAD

**Issue by dwhite21787** [usnationalarchives/digital-preservation#31]
Would you consider it worthwhile to add a section to the Software and Code plan related to "where a working copy of the software may be found" if a copy is not in this agency's collections? For NARA, it may be that LoC or NIST or a Presidential library may have secured a contemporaneous copy of software related to the object(s) being described. It may be worthwhile to know either that resource exists, or that a copy may need to be secured by this or another agency.

**Comment by dangormanjr** [comment]
I second dhwhite21787's comments. Knowing about repositories with requisite technology and hardware would help with redundancy and media archaeology. There is a need for a list of technology repositories, separate from lists of archival document repositories (a project that started in the Great Depression, but was never [finished](https://www.jstor.org/stable/40291617), incidentally).

**Comment by lljohnston** [comment]
@dwhite21787 That's a big potential undertaking that's outside of NARA's scope. I'm not sure how we'd keep up a list of those external resources in our plans, which are focused on our internal capabilities. I would love to see a community effort to document who has which vintage software programs in their possession that they also can use, whether by license or fair use. And who has properly licensed or fair use emulation VMs. Maybe this is a topic for the Software Preservation Network.

**Comment by dwhite21787** [comment]
@lljohnston 
>  potential undertaking that's outside of NARA's scope. I'm not sure how we'd keep up a list of those external resources 

Fair point.

> which are focused on our internal capabilities. 

How does NARA track the availability of their internal available working software copies?
That might spur on your next thought, which I agree with. 

> I would love to see a community effort to document who has which vintage software programs...

**Comment by lljohnston** [comment]
We have a couple of mechanisms for tracking what we have approved for use inside NARA - those processes are not managed by the digital preservation unit. We are looking at how to better document the approval process and tracking of software packages for digital preservation planning.
