### ISSUE TITLE
Geospatial Formats: GeoPackage

### ISSUE THREAD

**Issue by juddpatterson** [usnationalarchives/digital-preservation#33]
I work for the National Park Service where we are working to publish our digital assets in open, machine-readable formats that can be easily transferred to NARA. In the geospatial domain we are moving content from proprietary formats like ESRI personal geodatabases and aiming for the Preferred or Acceptable formats on the NARA website: https://www.archives.gov/records-mgmt/policy/transfer-guidance-tables.html#geospatialformats

One missing format that has gained a lot of traction across the Department of Interior (and beyond) is the GeoPackage (https://www.geopackage.org/). First approved by the Open Geospatial Consortium in 2014, this open standard supports vector features, tiled imagery, and non-spatial data in a single container, and we've seen it used for many products where a shapefile or similar formats are quite limiting.

Has the GeoPackage received any discussion within NARA? As we provide data publication guidance it would be most useful to know if this format is on the cusp of being an acceptable format (or not). Thank you!

**Comment by lljohnston** [comment]
No other agencies have brought up this format before, so we are adding it to our queue of formats to assess. We'll get back to you when both digital preservation and the Transfer Guidance team have completed a review.

**Comment by juddpatterson** [comment]
Thank you Leslie! Please reach out if there is anything that we can do to assist either team.

We noticed recently that the [LOC states the following](https://www.loc.gov/preservation/digital/formats/fdd/fdd000520.shtml):
> The Library of Congress Recommended Formats Statement (RFS) designates GeoPackage as a "preferred" format for GIS Vector Data, GIS Vector and Raster Combined data, as well as GIS Raster and Georeferenced Images for [GIS, Geospatial and Non-GIS Cartographic](https://www.loc.gov/preservation/resources/rfs/geo-carto.html) collection materials.

Here are also a few examples and relevant links to federal discussions about this format:
- https://www.usgs.gov/national-hydrography/news/nhd-and-wbd-now-available-geopackage-format
- https://www.fisheries.noaa.gov/inport/item/64219
- https://www.fgdc.gov/standards/sc_vote/GeoPackage/view

**Comment by eengland** [comment]
Hi Judd,

Thank you for providing this additional information. We wanted to let you know that we have added GeoPackage to the Digital Preservation Framework and the updated version of the Risk Matrix and Preservation Action Plans have been uploaded here. It has the NARA ID NF00795. I welcome any feedback you have! GeoPackage is still under review for the Transfer Guidance by a separate team, and we'll keep you updated.

Elizabeth
NARA Digital Preservation Unit

**Comment by eengland** [comment]
Judd,

GeoPackage is now added to the Transfer Guidance as a Preferred Format: [https://www.archives.gov/records-mgmt/policy/transfer-guidance-tables.html#geospatialformats](https://www.archives.gov/records-mgmt/policy/transfer-guidance-tables.html#geospatialformats)

Elizabeth
