### ISSUE TITLE
application programming interface (API) 

### ISSUE THREAD

**Issue by osherenko** [usnationalarchives/digital-preservation#34]
Is an API available for browsing archive data, for example, in Python?

**Comment by hannahlwang** [comment]
Thanks for your question. While we do not provide an API for the Digital Preservation Framework, we do make the information available as [Linked Open Data](https://www.archives.gov/preservation/digital-preservation/linked-data) for analysis and reuse.

If you are interested in accessing data about archival holdings, the [National Archives Catalog](https://catalog.archives.gov/), which is the online portal to records held at the National Archives, does have an [API for accessing catalog data](https://catalog.archives.gov/api/v2/api-docs/).

Depending on your needs and interests, we also have a list on our website of other [available datasets from the National Archives](https://www.archives.gov/open/available-datasets.html).
