### ISSUE TITLE
Consider using IETF "MIME types" to describe document formats

### ISSUE THREAD

**Issue by masinter** [usnationalarchives/digital-preservation#35]
There is an international standard for [MIME types](https://www.rfc-editor.org/rfc/rfc2046), and a [public registry](https://www.iana.org/assignments/media-types/media-types.xhtml) maintained by IANA.
MIME provides a mechanism for labelling content as stored or transmitted by email or HTTP.

MIME is widely used and understood. Using MIME type labels offers some kinds of categories and a mechanism for extension and a greater likelihood of adoption and availability of software for interpretation and conversion.

In addition, if there is need for finer granularity of format description, there are even IETF specifications for additional labelling attributes for file formats.

The current NARA descriptions of file formats could use a framework for categorization of media types.

**Comment by hannahlwang** [comment]
Thanks for your comment @masinter. Currently, we do map to MIME types in the [Preservation Action Plans for individual file formats](https://github.com/usnationalarchives/digital-preservation/tree/master/Digital_Preservation_Plan_Spreadsheet). In those plans, we also map to other available standards and frameworks for identifying and characterizing file formats, including PRONOM and the Library of Congress FDDs. As you note, MIME types are widely used and it is important to us to make sure to identify direct mappings between our framework and other resources, where possible.

**Comment by masinter** [comment]
@hannahlwang I see now on further examination that there is a column for MIME type in the spreadsheet.
I had only looked at the summary documents, such as [the pages about Digital Audio records](https://github.com/usnationalarchives/digital-preservation/blob/master/Digital_Audio_Formats/NARA_PreservationActionPlan_DigitalAudio_20220714.pdf)

And there are [some inadequacies](https://masinter.blogspot.com/2010/06/mime-and-web.html)
