### ISSUE TITLE
Markdown as base release format

### ISSUE THREAD

**Issue by nkrabben** [usnationalarchives/digital-preservation#36]
Would it be possible to release these reports as markdown text first with a PDF version derived from it?

While it's useful to have the PDFs version-controlled via git, because PDF is a binary format, the logged changes aren't atomic. For example, I can learn that the Digital Audio Format plan has been updated a few times. 
https://github.com/usnationalarchives/digital-preservation/commits/master/Digital_Audio_Formats

But, I can't tell how it's been changed unless I read each version side by side.

Switching to using markdown, or another text format, as the base release format would help me understand how these plans are evolving overtime and if there are specific changes that I want to pull into our practice.

**Comment by eengland** [comment]
Hi Nick, thank you for the suggestion. This isn't something we had thought of before, but makes sense. I will discuss with the team and we'll get back to you soon.

**Comment by eengland** [comment]
Nick,

We've added all the record category plans as markdown, in a [new folder here](https://github.com/usnationalarchives/digital-preservation/tree/master/Digital_Preservation_Record_Categories). We'll be publishing updates next month for some of these and will share those as both markdown and the PDFs. Let us know if you have any feedback.

Elizabeth
