### ISSUE TITLE
Template files for preservation action plans

### ISSUE THREAD

**Issue by asciim0** [usnationalarchives/digital-preservation#37]
I see that your preservation action plans header reference versions of the template used (e.g., "Template: 202105" for NARA_PreservationActionPlan_DigitalDesignAndVectorGraphics_20240322.pdf) but couldn't find the templates themselves on this github repo. This might very well be me just overseeing them. Could you let me know where they are? If they are not on the repo yet, would you consider adding them? As the changelog includes info on the templates being updated this might be helpful?
Thank you!

**Comment by eengland** [comment]
Hi Micky,

We've made the [template](https://github.com/usnationalarchives/digital-preservation/blob/master/Digital_Preservation_Record_Categories/NARA_PreservationActionPlan_Template.docx) available as a Word doc in this [new folder](https://github.com/usnationalarchives/digital-preservation/tree/master/Digital_Preservation_Record_Categories). Thank you for the suggestion to add it! Let us know if you have any feedback.

Elizabeth

**Comment by asciim0** [comment]
Looks great, thanks!
