### ISSUE TITLE
Paper records - which format category do they fit under?

### ISSUE THREAD

**Issue by rexbradford** [usnationalarchives/digital-preservation#5]
There are many formats discussed, but it's not clear which one applies to paper records to be scanned/digitized.  They aren't simply "still images" - besides being multi-page, there is the issue of optical character recognition (OCR) and metadata (titles and more).  PDF is one format, currently used for the online JFK records, but not the only choice.  PDF itself is also an umbrella format which has many internal choices: internal image format, scanning resolution and bit depth, etc.

So it seems clear that scanned documents should be considered as its own topic.

**Comment by lljohnston** [comment]
It's an interesting point. The file formats, regardless of what type of content they represent, have essentially the same associated risks so we haven't emphasized if they apply to both borndist-digital and digitized records. Our transfer guidance has focused on born-digital records and formats, but of course many of the formats also apply to digitized records. We can definitely make that additional distinction in later versions.
